### ISSUE TITLE
Predict breaks when the object the results are assigned to already exists

### ISSUE THREAD

**Issue by timyoungren** [jaak-s/extraTrees#4]
I have been trying to baseline extraTrees against other algorithms, but I consistently receive an error when assigning the prediction results to a variable that already exists. This happens with the example code as well. Below are the results when I run the code for the second time.

```
> ## Generating artificial data:
> n <- 1000  ## number of samples
> p <- 5     ## number of dimensions
> ## x - inputs
> ## y - outputs to predict
> x <- matrix(runif(n*p), n, p)
> y <- (x[,1]>0.5) + 0.8*(x[,2]>0.6) + 0.5*(x[,3]>0.4) + 0.1*runif(nrow(x))
> ## Training and predicting with ExtraTrees:
> et <- extraTrees(x, y)
> yhat <- predict(et, x)
```
**Error in ls(envir = envir, all.names = private) : 
  invalid 'envir' argument**

I tried removing the yhat and et variables before rebuilding and that seemed to help, but it does not solve the issue.

I am running on RStudio Server Version 0.98.1102 with R version 3.2.0.
> version
               _                           
platform       x86_64-redhat-linux-gnu     
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          2.0                         
year           2015                        
month          04                          
day            16                          
svn rev        68180                       
language       R                           
version.string R version 3.2.0 (2015-04-16)
nickname       Full of Ingredients        

Any help with this is appreciated. Thank you. 

Tim

**Comment by jaak-s** [comment]
I cannot reproduce this bug. I tried running the code multiple times and no problems, for both standard R (version 3.2.4) and RStudio.

As you are using RStudio Server, that might be a problem. Can you try it in standard R?
