### ISSUE TITLE
Issue with R 3.5

### ISSUE THREAD

**Issue by coryandar** [jaak-s/extraTrees#9]
I recently upgraded my R to version 3.5. Since then I have been unable to load extraTrees, it always results in completely crashing RStudio, version 1.1.456.  

If this package not compatible with the latest version? Would a downgrade to version 3.4 be the best course of action?  

Thanks

**Comment by jaak-s** [comment]
I've 3.5 installed with `extraTrees`. Loading the package has no problem. Probably issue with your installation or RStudio itself. You can try reinstalling RStudio.
